### ISSUE TITLE
Hey Copycat!

### ISSUE THREAD

**Issue by zenycrypto** [cpuchain/cpuchain#10]
Hey copycat!

Copying my work from bitzeny to cpuchain is a fun thing to do!

Blocking my main account @cryptozeny from your repo and from @cpuchain repo was a big mistake for you to do! @minkcrypto 

Cause you can delete my account from discord for doxxing scammers like you, however I can do doxxing on Github with my sub account at anytime I want!

Github will delete my alt accounts but they will never delete my real account so fuck you @minkcrypto 

Dramas and doxxing are allowed to do!

I will dox your private information, about your workplace and your real name, your face pic!

![캡처](https://user-images.githubusercontent.com/59803886/72223903-60f24980-35b7-11ea-9b0a-0eb087f124dd.PNG)
![캡처2](https://user-images.githubusercontent.com/59803886/72223904-60f24980-35b7-11ea-9ae2-47062fc62ebf.PNG)
![캡처3](https://user-images.githubusercontent.com/59803886/72223906-60f24980-35b7-11ea-9de3-aa4a082fb075.PNG)
![캡처4](https://user-images.githubusercontent.com/59803886/72223907-618ae000-35b7-11ea-9436-bb4f27571d49.PNG)

You scum's real name is Aung Khaing Min, and you work in Si Daw Gyi Cafe,

number is +95 9 761 314777 and the address is Yangon, Myanmar (Burma)

I will hire some killers from Deepweb and send some assassins to kill you while you are in a workplace, as a compensate for my Discord account ban from you!!!!

FUCK YOU AUNG KHAING MIN!!!!

You selfish yellow monkey you wouldn't be able to ban my @cryptozeny account this time!

**Comment by minkcrypto** [comment]
You can't stop doxxing me aren't you, after being banned by discord for doxxing me and now you are posting my workshop address, tell numbers, and threating me to kill me, what a drama.
